AccuTecMan/stages

src/app/app-routing.module.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/common/app-common.module.ts, src/app/common/components/header.component.ts, src/app/core/authentication/index.ts, src/app/core/index.ts, src/app/features/overview/containers/components/overview.component.ts, src/index.html, src/styles.scss
Addint the initial version of the auth page
=> Addint the initial version of the auth page

src/app/app.component.ts, src/app/common/app-common.module.ts, src/app/common/components/header.component.ts, src/app/common/components/sidenav-list.component.ts, src/app/core/authentication/components/login.component.ts, src/app/core/services/auth.service.ts, src/app/core/store/actions.ts, src/app/core/store/reducer.ts, src/app/core/store/selectors.ts
Creating login page and side nav menu
=> Creating login page and side nav menu

.gitignore, src/app/core/authentication/components/login.component.ts
=> refine login page

src/app/common/components/header.component.ts, src/app/common/components/sidenav-list.component.ts
=> Refine the meny style

angular.json, package-lock.json, package.json
=> update to Angular 17

src/app/common/components/header.component.ts
=> Align main title

src/app/core/index.ts, src/app/core/operators/index.ts, src/app/core/operators/load-entity.ts, src/app/features/customers/customer.module.ts, src/app/features/customers/guards/customers.guard.ts, src/app/features/customers/guards/index.ts, src/app/features/customers/models/customer.ts, src/app/features/customers/models/index.ts, src/app/features/customers/services/customer.service.ts, src/app/features/customers/services/index.ts, src/app/features/customers/store/actions/actions.ts, src/app/features/customers/store/actions/index.ts, src/app/features/customers/store/effects/effects.ts, src/app/features/customers/store/effects/index.ts, src/app/features/customers/store/index.ts, src/app/features/customers/store/reducers/index.ts, src/app/features/customers/store/reducers/reducer.ts, src/app/features/customers/store/selectors/index.ts, src/app/features/customers/store/selectors/selectors.ts
Create Customers models, services and store
=> Create Customers models, services and store

src/app/features/customers/containers/components/customer.component.ts, src/app/features/customers/containers/customers.container.ts, src/app/features/customers/store/selectors/selectors.ts, src/app/material.module.ts
Create cards to display customers
=> Create cards to display customers

src/app/app.component.ts, src/app/common/components/sidenav-list.component.ts, src/app/features/customers/containers/components/customer.component.ts, src/app/features/customers/containers/customers.container.ts, src/app/features/customers/customer.module.ts, src/styles.scss
=> Adding filter to customers

src/app/app.component.ts, src/app/core/authentication/components/login.component.ts, src/app/features/customers/containers/components/customer.component.ts
=> Change login page color

src/app/features/customers/containers/components/customer.component.ts, src/app/features/customers/containers/customers.container.ts
=> Fix a search term issue

src/app/features/customers/containers/components/customer.component.ts, src/styles.scss
=> add new button

src/app/features/customers/containers/components/customer.component.ts
=> add chip to active-inactive

src/app/features/customers/containers/components/add-edit.component.ts, src/app/features/customers/containers/components/customer.component.ts, src/app/features/customers/customer.module.ts, src/app/features/customers/services/customer.service.ts
=> Add edit customer

src/app/features/customers/containers/components/customer.component.ts
Adding responsive changes to customers
=> Adding responsive changes to customers

src/app/common/components/header.component.ts, src/app/features/customers/containers/components/add-edit.component.ts, src/app/features/customers/containers/components/customer.component.ts
more changes around the customers
=> more changes around the customers

src/app/features/cutting-sheets/models/cutting-sheet.ts, src/app/features/cutting-sheets/models/stage.ts
=> Cutting Sheets models

src/app/features/cutting-sheets/models/index.ts, src/app/features/cutting-sheets/models/type.ts, src/app/features/cutting-sheets/services/cutting-sheets.service.ts, src/app/features/cutting-sheets/services/types.service.ts
adding cutting sheets and types services
=> adding cutting sheets and types services

src/app/features/customers/containers/components/customer.component.ts, src/app/features/cutting-sheets/cutting-sheets.module.ts, src/app/features/cutting-sheets/guards/types.guard.ts, src/app/features/cutting-sheets/services/index.ts, src/app/features/cutting-sheets/store/actions/index.ts, src/app/features/cutting-sheets/store/actions/types.actions.ts, src/app/features/cutting-sheets/store/effects/effects.ts, src/app/features/cutting-sheets/store/effects/index.ts, src/app/features/cutting-sheets/store/index.ts, src/app/features/cutting-sheets/store/reducers/feature.reducer.ts, src/app/features/cutting-sheets/store/reducers/index.ts, src/app/features/cutting-sheets/store/reducers/types.reducer.ts, src/app/features/cutting-sheets/store/selectors/feature.selectors.ts, src/app/features/cutting-sheets/store/selectors/index.ts, src/app/features/cutting-sheets/store/selectors/type.selectors.ts
=> Adding types to the Store

src/app/app.component.ts
Changing the background when in Devmode
=> Changing the background when in Devmode

angular.json
=> Set Google Analytics to false

src/app/base/models/index.ts, src/app/base/models/job-type.ts, src/app/base/models/stage-template.ts, src/app/base/services/job-types.service.ts, src/app/base/services/stage-templates.service.ts, src/app/base/store/actions/job-types.actions.ts, src/app/base/store/reducers/job-types.reducer.ts, src/app/features/customers/store/selectors/selectors.ts, src/app/features/cutting-sheets/cutting-sheets.module.ts, src/app/features/cutting-sheets/guards/cutting-sheets.guard.ts, src/app/features/cutting-sheets/models/cutting-sheet.ts, src/app/features/cutting-sheets/models/index.ts, src/app/features/cutting-sheets/services/index.ts, src/app/features/cutting-sheets/store/actions/cutting-sheets.actions.ts, src/app/features/cutting-sheets/store/effects/effects.ts, src/app/features/cutting-sheets/store/index.ts, src/app/features/cutting-sheets/store/reducers/index.ts, src/app/features/cutting-sheets/store/reducers/reducer.ts, src/app/features/cutting-sheets/store/selectors/selectors.ts
=> Adding Cutting Sheets store

src/app/features/customers/containers/components/customer.component.ts, src/app/features/customers/containers/customers.container.ts, src/app/features/customers/store/selectors/selectors.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets.component.ts, src/app/features/cutting-sheets/containers/cutting-sheets.container.ts, src/app/features/cutting-sheets/cutting-sheets.module.ts, src/app/features/cutting-sheets/store/index.ts, src/app/features/cutting-sheets/store/selectors/selectors.ts
=> Display Cutting Sheets

src/app/features/customers/containers/components/customer.component.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets.component.ts, src/app/features/cutting-sheets/models/cutting-sheet.ts
Refine cutting sheet and customers pages
=> Refine cutting sheet and customers pages

src/app/features/customers/containers/components/customer.component.ts, src/app/features/customers/containers/customers.container.ts, src/app/features/customers/store/selectors/selectors.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets.component.ts, src/styles.scss
Customers show active inactive accelerator
=> Customers show active inactive accelerator

src/app/features/customers/containers/components/customer.component.ts, src/app/features/customers/containers/customers.container.ts, src/app/features/customers/store/selectors/selectors.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets.component.ts
Show customers inactive along with term
=> Show customers inactive along with term

src/app/features/cutting-sheets/models/search-criteria.ts, src/app/features/cutting-sheets/store/index.ts, src/app/features/cutting-sheets/store/reducers/index.ts, src/app/features/cutting-sheets/store/reducers/reducer.ts, src/app/features/cutting-sheets/store/selectors/selectors.ts
Adjust store to have Search Criteria
=> Adjust store to have Search Criteria

src/app/features/cutting-sheets/containers/components/cutting-sheets.component.ts, src/app/features/cutting-sheets/models/index.ts, src/app/features/cutting-sheets/services/cutting-sheets.service.ts, src/app/features/cutting-sheets/store/effects/effects.ts, src/app/features/cutting-sheets/store/index.ts, src/app/features/cutting-sheets/store/reducers/index.ts, src/app/features/cutting-sheets/store/reducers/reducer.ts, src/app/features/cutting-sheets/store/selectors/selectors.ts
Adding multiple wheres to the condition
=> Adding multiple wheres to the condition

src/app/features/cutting-sheets/containers/components/cutting-sheets.component.ts, src/app/features/cutting-sheets/containers/cutting-sheets.container.ts, src/app/features/cutting-sheets/services/cutting-sheets.service.ts, src/app/features/cutting-sheets/store/actions/cutting-sheets.actions.ts, src/app/features/cutting-sheets/store/index.ts, src/app/features/cutting-sheets/store/reducers/reducer.ts
Add functionality to criteria combo
=> Add functionality to criteria combo

src/app/app-routing.module.ts, src/app/base/guards/customers.guard.ts, src/app/base/services/customer.service.ts, src/app/base/store/actions/customers.actions.ts, src/app/base/store/effects/effects.ts, src/app/base/store/reducers/customer.reducer.ts, src/app/base/store/reducers/job-types.reducer.ts, src/app/base/store/reducers/stage-templates.reducer.ts, src/app/base/store/selectors/customers.selectors.ts, src/app/base/store/selectors/index.ts, src/app/base/store/selectors/job-types.selectors.ts, src/app/base/store/selectors/stage-templates.selectors.ts, src/app/core/models/load-status.interface.ts, src/app/features/customers/containers/components/add-edit.component.ts, src/app/features/customers/containers/customers.container.ts, src/app/features/customers/customer.module.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets.component.ts, src/app/features/cutting-sheets/cutting-sheets.module.ts, src/app/features/cutting-sheets/services/cutting-sheets.service.ts, src/app/features/cutting-sheets/store/reducers/reducer.ts, src/app/features/cutting-sheets/store/selectors/selectors.ts
adding customer store and components
=> adding customer store and components

src/app/base/store/selectors/customers.selectors.ts, src/app/base/store/selectors/index.ts, src/app/features/customers/containers/customers.container.ts
fixin id with zero in customers
=> fixin id with zero in customers

src/app/base/services/customer.service.ts, src/app/features/customers/containers/components/customer.component.ts, src/app/features/customers/containers/customers.container.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets.component.ts
=> Align cutting sheets cards

src/app/app-routing.module.ts, src/app/base/store/selectors/customers.selectors.ts, src/app/base/store/selectors/index.ts, src/app/features/customers/containers/components/add-edit.component.ts, src/app/features/customers/containers/components/customer.component.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets.component.ts, src/app/features/cutting-sheets/containers/cutting-sheets.container.ts
Making cutting sheets cards clickable
=> Making cutting sheets cards clickable

src/app/features/cutting-sheets/containers/components/cutting-sheets.component.ts, src/app/material.module.ts
=> add customers autocomplete

src/app/features/cutting-sheets/containers/components/cutting-sheets.component.ts, src/app/features/cutting-sheets/containers/cutting-sheets.container.ts
=> Filter by PO number

src/app/base/store/selectors/index.ts, src/app/base/store/selectors/job-types.selectors.ts, src/app/features/cutting-sheets/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets.component.ts, src/app/features/cutting-sheets/containers/cutting-sheets.container.ts, src/app/features/cutting-sheets/cutting-sheets.module.ts
adding and editing cutting sheets
=> adding and editing cutting sheets

src/app/features/cutting-sheets/containers/components/cutting-sheets.component.ts, src/app/features/cutting-sheets/cutting-sheets.module.ts
=> load all catalogs

src/app/features/cutting-sheets/containers/add-edit.container.ts, src/app/features/cutting-sheets/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/containers/components/list.component.ts, src/app/features/cutting-sheets/containers/list.container.ts, src/app/features/cutting-sheets/cutting-sheets.module.ts
Create Cutting Sheets containers
=> Create Cutting Sheets containers

src/app/common/components/header.component.ts, src/app/common/components/sidenav-list.component.ts, src/app/core/authentication/components/login.component.ts, src/app/features/customers/containers/components/add-edit.component.ts, src/app/features/customers/containers/components/customer.component.ts, src/app/features/cutting-sheets/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/containers/components/list.component.ts
New control flow commands were applied
=> New control flow commands were applied

src/app/base/guards/customers.guard.ts, src/app/base/services/customer.service.ts, src/app/base/store/selectors/customers.selectors.ts, src/app/features/customers/containers/components/list.component.ts, src/app/features/customers/customer.module.ts, src/app/features/cutting-sheets/containers/add-edit.container.ts, src/app/features/cutting-sheets/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/containers/components/list.component.ts, src/app/features/cutting-sheets/cutting-sheets.module.ts, src/app/features/cutting-sheets/models/current-stage.ts, src/app/features/cutting-sheets/models/cutting-sheet.ts, src/app/features/cutting-sheets/models/stage.ts, src/app/features/cutting-sheets/services/cutting-sheets.service.ts, src/app/features/cutting-sheets/store/effects/effects.ts
=> Adding current cutting sheet

src/app/core/services/auth.service.ts, src/app/features/customers/containers/components/list.component.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts, src/app/features/cutting-sheets/containers/components/index.ts, src/app/features/cutting-sheets/containers/components/list.component.ts, src/app/features/cutting-sheets/containers/index.ts, src/app/features/cutting-sheets/containers/stages.container.ts, src/app/features/cutting-sheets/cutting-sheets.module.ts, src/app/features/cutting-sheets/guards/stages.guard.ts, src/app/features/cutting-sheets/store/actions/cutting-sheets.actions.ts, src/app/features/cutting-sheets/store/effects/effects.ts, src/app/features/cutting-sheets/store/reducers/reducer.ts, src/styles.scss
Adding stages to the selected cutting sheet
=> Adding stages to the selected cutting sheet

src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts, src/app/features/cutting-sheets/containers/stages.container.ts, src/app/features/cutting-sheets/store/index.ts, src/app/features/cutting-sheets/store/reducers/index.ts, src/app/features/cutting-sheets/store/reducers/reducer.ts, src/app/features/cutting-sheets/store/selectors/selectors.ts
include selected cutting sheet with stages
=> include selected cutting sheet with stages

src/app/base/store/selectors/customers.selectors.ts, src/app/base/store/selectors/job-types.selectors.ts, src/app/features/customers/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/containers/add-edit.container.ts, src/app/features/cutting-sheets/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts, src/app/features/cutting-sheets/containers/components/list.component.ts, src/app/features/cutting-sheets/cutting-sheets.module.ts, src/app/features/cutting-sheets/guards/select-sheet.guard.ts
=> First cutting sheets form

src/app/features/cutting-sheets/containers/components/add-edit.component.ts
=> updating cutting sheets

src/app/base/store/selectors/index.ts, src/app/base/store/selectors/stage-templates.selectors.ts, src/app/features/cutting-sheets/containers/add-edit.container.ts, src/app/features/cutting-sheets/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/services/cutting-sheets.service.ts
=> Add new cutting sheet

src/app/features/cutting-sheets/containers/add-edit.container.ts, src/app/features/cutting-sheets/containers/components/add-edit.component.ts
=> Remove unneeded code

src/app/features/cutting-sheets/containers/components/add-edit.component.ts
=> Arrange form fields

src/app/features/cutting-sheets/containers/components/list.component.ts
=> Fix some card spaces

src/app/base/store/selectors/index.ts, src/app/features/customers/containers/components/add-edit.component.ts, src/app/features/customers/containers/components/list.component.ts, src/app/features/customers/containers/customers.container.ts, src/app/features/cutting-sheets/containers/add-edit.container.ts, src/app/features/cutting-sheets/services/cutting-sheets.service.ts
=> Fix customer creating bug

src/app/base/models/stage-template.ts, src/app/features/customers/containers/customers.container.ts, src/app/features/cutting-sheets/containers/add-edit.container.ts, src/app/features/cutting-sheets/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts, src/app/features/cutting-sheets/containers/components/list.component.ts, src/app/features/cutting-sheets/models/current-stage.ts, src/app/features/cutting-sheets/models/stage.ts, src/app/features/cutting-sheets/services/cutting-sheets.service.ts, src/app/features/cutting-sheets/store/effects/effects.ts, src/app/material.module.ts
=> Displaying all the stages

src/app/features/customers/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/containers/add-edit.container.ts, src/app/features/cutting-sheets/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts, src/app/features/cutting-sheets/containers/components/list.component.ts
=> Adding step buttons

src/app/base/store/effects/effects.ts, src/app/features/customers/containers/components/list.component.ts, src/app/features/customers/containers/customers.container.ts, src/app/features/cutting-sheets/containers/add-edit.container.ts, src/app/features/cutting-sheets/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts, src/app/features/cutting-sheets/containers/list.container.ts, src/app/features/cutting-sheets/containers/stages.container.ts, src/app/features/cutting-sheets/services/cutting-sheets.service.ts, src/app/features/cutting-sheets/store/actions/cutting-sheets.actions.ts, src/app/features/cutting-sheets/store/effects/effects.ts, src/app/features/cutting-sheets/store/reducers/reducer.ts
=> Set stage initally

src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts, src/app/features/cutting-sheets/containers/stages.container.ts, src/app/features/cutting-sheets/services/cutting-sheets.service.ts, src/app/features/cutting-sheets/store/actions/cutting-sheets.actions.ts, src/app/features/cutting-sheets/store/effects/effects.ts, src/app/features/cutting-sheets/store/reducers/reducer.ts
=> Update stage while changing

.eslintrc.json, angular.json, package-lock.json, package.json, src/app/app.component.ts, src/app/base/models/stage-template.ts, src/app/base/services/customer.service.ts, src/app/base/services/stage-templates.service.ts, src/app/base/store/effects/effects.ts, src/app/core/core.module.ts, src/app/core/services/auth.service.ts, src/app/features/customers/containers/components/add-edit.component.ts, src/app/features/customers/containers/customers.container.ts, src/app/features/cutting-sheets/containers/add-edit.container.ts, src/app/features/cutting-sheets/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts, src/app/features/cutting-sheets/containers/components/list.component.ts, src/app/features/cutting-sheets/models/cutting-sheet.ts, src/app/features/cutting-sheets/models/index.ts, src/app/features/cutting-sheets/models/stage.ts, src/app/features/cutting-sheets/models/timestamp.ts, src/app/features/cutting-sheets/services/cutting-sheets.service.ts, src/app/features/cutting-sheets/store/actions/cutting-sheets.actions.ts, src/app/features/cutting-sheets/store/effects/effects.ts
=> Adding lint libraries

src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts, src/app/features/cutting-sheets/containers/components/list.component.ts
=> sateg-date

src/app/base/models/index.ts, src/app/base/models/stage-map.ts, src/app/base/models/stage-template.ts, src/app/common/components/header.component.ts, src/app/features/cutting-sheets/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts, src/app/features/cutting-sheets/containers/stages.container.ts, src/app/features/cutting-sheets/models/current-stage.ts, src/app/features/cutting-sheets/models/cutting-sheet.ts, src/app/features/cutting-sheets/models/stage.ts, src/index.html
=> creating new stage model

src/app/base/guards/stage-map.guard.ts, src/app/base/models/index.ts, src/app/base/models/stage-map.ts, src/app/base/services/stage-templates.service.ts, src/app/base/store/actions/index.ts, src/app/base/store/actions/stage-templates.actions.ts, src/app/base/store/effects/effects.ts, src/app/base/store/reducers/feature.reducer.ts, src/app/base/store/reducers/stage-map.reducer.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts, src/app/features/cutting-sheets/containers/stages.container.ts, src/app/features/cutting-sheets/cutting-sheets.module.ts, src/app/features/cutting-sheets/models/cutting-sheet.ts
=> Adding StageMap to the store

src/app/base/services/stage-templates.service.ts, src/app/features/cutting-sheets/containers/components/list.component.ts
=> change label style

src/app/base/store/selectors/index.ts, src/app/base/store/selectors/stage-templates.selectors.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts, src/app/features/cutting-sheets/containers/components/list.component.ts, src/app/features/cutting-sheets/containers/list.container.ts, src/app/features/cutting-sheets/containers/stages.container.ts, src/app/features/cutting-sheets/models/search-criteria.ts, src/app/features/cutting-sheets/services/cutting-sheets.service.ts
Adding stages list to the component
=> Adding stages list to the component

src/app/base/store/selectors/stage-templates.selectors.ts, src/app/features/cutting-sheets/containers/components/list.component.ts, src/app/features/cutting-sheets/models/cutting-sheet.ts, src/app/features/cutting-sheets/services/cutting-sheets.service.ts
Filtering by stage NOT WORKING
=> Filtering by stage NOT WORKING

src/app/features/cutting-sheets/services/cutting-sheets.service.ts
=> Filter by Stage ID

src/app/base/store/selectors/stage-templates.selectors.ts, src/app/features/cutting-sheets/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/containers/components/list.component.ts, src/styles.scss
Change cutting sheet customers
=> Change cutting sheet customers

src/app/features/cutting-sheets/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/containers/components/list.component.ts, src/app/features/cutting-sheets/services/cutting-sheets.service.ts
=> Fix saving the cutting sheet

src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts
=> Step data WIP

src/app/features/cutting-sheets/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts, src/app/features/cutting-sheets/containers/components/list.component.ts, src/app/features/cutting-sheets/models/cutting-sheet.ts, src/app/features/cutting-sheets/models/search-criteria.ts, src/app/features/cutting-sheets/services/cutting-sheets.service.ts, src/app/features/cutting-sheets/store/reducers/reducer.ts
Adding the isActive field and filters
=> Adding the isActive field and filters

src/app/base/store/selectors/customers.selectors.ts, src/app/base/store/selectors/index.ts, src/app/features/cutting-sheets/containers/add-edit.container.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts
=> Filter by Active

src/app/features/cutting-sheets/containers/components/close-dialog.component.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts, src/app/features/cutting-sheets/services/cutting-sheets.service.ts
=> Creating dialog box

README.md, src/app/features/cutting-sheets/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/containers/components/list.component.ts, src/app/features/cutting-sheets/models/cutting-sheet.ts
=> Add notes field

src/app/features/cutting-sheets/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts, src/app/features/cutting-sheets/containers/stages.container.ts, src/app/features/cutting-sheets/services/cutting-sheets.service.ts
Display the current date on stages
=> Display the current date on stages

src/app/features/cutting-sheets/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts
Display date when last stage is done
=> Display date when last stage is done

src/app/features/cutting-sheets/containers/components/list.component.ts
=> Reduce card title font size

src/app/features/cutting-sheets/containers/components/list.component.ts
small changes on the interface
=> small changes on the interface

package-lock.json, package.json, src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts, src/app/features/cutting-sheets/containers/stages.container.ts, src/app/features/cutting-sheets/services/cutting-sheets.service.ts, src/app/features/cutting-sheets/store/actions/cutting-sheets.actions.ts, src/app/features/cutting-sheets/store/effects/effects.ts, src/app/features/cutting-sheets/store/reducers/reducer.ts, src/styles.scss, tsconfig.json
Adding notes to each step on the stages
=> Adding notes to each step on the stages

src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts
final entering notes on each step
=> final entering notes on each step

src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts
Fix when notes field is undefined
=> Fix when notes field is undefined

src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts
Fix when saving last step notes
=> Fix when saving last step notes

src/app/features/cutting-sheets/containers/components/close-dialog.component.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts
Allow edit a sheet after close it
=> Allow edit a sheet after close it

src/app/features/cutting-sheets/containers/components/add-edit.component.ts, src/app/features/cutting-sheets/containers/components/cutting-sheets-stages.component.ts, src/app/features/cutting-sheets/containers/components/list.component.ts, src/app/features/cutting-sheets/models/cutting-sheet.ts, src/app/features/cutting-sheets/models/search-criteria.ts, src/app/features/cutting-sheets/services/cutting-sheets.service.ts, src/app/features/cutting-sheets/store/effects/effects.ts, src/app/features/cutting-sheets/store/reducers/reducer.ts
=> Show done instead of active

src/app/features/customers/containers/components/add-edit.component.ts, src/app/features/customers/containers/components/index.ts, src/app/features/customers/containers/index.ts, src/app/features/customers/customers.routes.ts
=> Fix routes after standalone

src/app/core/services/auth.service.ts
Change navigate route after login
=> Change navigate route after login

src/app/base/models/stage-template.ts, src/app/base/services/customer.service.ts, src/app/core/services/auth.service.ts, src/app/features/customers/customers.routes.ts, src/app/features/cutting-sheets/containers/components/list.component.ts
=> Remove no needed code

package-lock.json, package.json, src/app/features/cutting-sheets/containers/components/list.component.ts
update libraries and add index to a for loop
=> update libraries and add index to a for loop

src/app/features/cutting-sheets/containers/components/list.component.ts, src/app/features/cutting-sheets/store/reducers/reducer.ts
set today as default to retrieve rows
=> set today as default to retrieve rows
